spring:
  application:
    name: property-access-service
  profiles:
    active: dev

server:
  port: ${port:8081}
  
management:
  endpoints:
    web:
      exposure:
        include: refresh
        
